### ISSUE TITLE
Epochs

### ISSUE THREAD

**Issue by kkkkkaran** [YunYang1994/tensorflow-yolov3#118]
I am new to  ML and Tensorflow, and could not really wrap my head around the code. Does a single run of quick train mean 1 epoch? and if yes, how do I run multiple epochs?

**Comment by Guddu327** [comment]
The no of epochs is mentioned inside the quick_train.py, and no it does not  mean 1 epoch. Depending yon your batch size and the no of of steps you are running for, the no of epochs is calculated.
