### ISSUE TITLE
Out of Index Error arrising in Utils.py

### ISSUE THREAD

**Issue by sandipan-basak** [YunYang1994/tensorflow-yolov3#121]
=> STEP       3250 [TRAIN]:	loss_xy: 2.1980 	loss_wh: 0.0426 	loss_conf:    nan 	loss_class:    nan
Traceback (most recent call last):
  File "quick_train.py", line 89, in <module>
    test_rec_value, test_prec_value = utils.evaluate(run_items[1], run_items[2])
  File "/swdata1/sandipanb/YunYang1994/tensorflow-yolov3/core/utils.py", line 345, in evaluate
    box_centers, box_sizes = true_boxes[:,0:2], true_boxes[:,2:4]
IndexError: too many indices for array

My no of classess = 3
train data strength = 2833
test data strength = 590
anchors.txt is created using kmeans.py anchor number = 9
Evaluate after every 250 steps
Save Internal Number after every 500 steps
Epochs running till 3250, then error is coming everytime.

Have any of you faced this problem, if so please help!!

**Comment by vahit19** [comment]
it seem that you was used yolo tiny model, please use 6 anchors coordinates for tiny, not 9 anchors.
please kindly chnge the get_kmeans(anno_result, 6) for v3 tiny in get_kmeans.py then train again your network with your new anchors from get_kmeans.py.

Best, Vahit
https://4deepanalytics.com/

**Comment by vahit19** [comment]
> => STEP 3250 [TRAIN]: loss_xy: 2.1980 loss_wh: 0.0426 loss_conf: nan loss_class: nan
> Traceback (most recent call last):
> File "quick_train.py", line 89, in
> test_rec_value, test_prec_value = utils.evaluate(run_items[1], run_items[2])
> File "/swdata1/sandipanb/YunYang1994/tensorflow-yolov3/core/utils.py", line 345, in evaluate
> box_centers, box_sizes = true_boxes[:,0:2], true_boxes[:,2:4]
> IndexError: too many indices for array
> 
> My no of classess = 3
> train data strength = 2833
> test data strength = 590
> anchors.txt is created using kmeans.py anchor number = 9
> Evaluate after every 250 steps
> Save Internal Number after every 500 steps
> Epochs running till 3250, then error is coming everytime.
> 
> Have any of you faced this problem, if so please help!!

it seem that you was used yolo tiny model, please use 6 anchors coordinates for tiny, not 9 anchors.
please kindly change the get_kmeans(anno_result, 6) for v3 tiny in get_kmeans.py then train again your network with your new anchors from get_kmeans.py.

Best, Vahit
https://4deepanalytics.com/
