### ISSUE TITLE
darknet模型转换问题

### ISSUE THREAD

**Issue by nobody-cheng** [YunYang1994/tensorflow-yolov3#139]
请问作者的yolov3.weights是根据darknet生成模型的模型吗？
我这里使用darknet生成的模型通过convert_weight.py文件转ckpt出现如下错误
![作者提供模型](https://user-images.githubusercontent.com/34908468/57516382-31fc4780-7347-11e9-9e4f-d0d237d106e4.PNG)
![错误](https://user-images.githubusercontent.com/34908468/57516390-37599200-7347-11e9-8a36-806857e31d8f.PNG)

**Comment by mkartikkumar** [comment]
请翻译成中文并阅读

please download weights [here](https://pjreddie.com/media/files/yolov3.weights) and keep them in the checkpoint folder and try running the script again

**Comment by nobody-cheng** [comment]
thanks

**Comment by computervisionlearner** [comment]
> 请问作者的yolov3.weights是根据darknet生成模型的模型吗？
> 我这里使用darknet生成的模型通过convert_weight.py文件转ckpt出现如下错误
> ![作者提供模型](https://user-images.githubusercontent.com/34908468/57516382-31fc4780-7347-11e9-9e4f-d0d237d106e4.PNG)
> ![错误](https://user-images.githubusercontent.com/34908468/57516390-37599200-7347-11e9-8a36-806857e31d8f.PNG)

你好，这个convert_weight.py脚本可以读取darknet的yolo.weight文件吗？我看它不是读取的tf.train.import_meta_graph(org_weights_path + '.meta') 这个.meta文件吗？
