### ISSUE TITLE
get_anchors() anchors疑问

### ISSUE THREAD

**Issue by nobody-cheng** [YunYang1994/tensorflow-yolov3#140]
def get_anchors(anchors_path, image_h, image_w):
    '''loads the anchors from a file'''
    with open(anchors_path) as f:
        anchors = f.readline()
    anchors = np.array(anchors.split(), dtype=np.float32)
    anchors = anchors.reshape(-1,2)
    anchors[:, 1] = anchors[:, 1] * image_h
    anchors[:, 0] = anchors[:, 0] * image_w
    return anchors.astype(np.int32)
为什么anchors要乘以resize后的宽高
给定的9个anchors对应到416*416

**Comment by YunYang1994** [comment]
建议去看论文

**Comment by cong235** [comment]
@YunYang1994 How can i gen new anchor for my data bro ?
