### ISSUE TITLE
路径正确，但总是无法导入 yolov3_coco_demo.ckpt

### ISSUE THREAD

**Issue by FangliangBai** [YunYang1994/tensorflow-yolov3#178]
我在Pycharm 从 readme 的 **3.1 Train VOC dataset** 开始做（其他未改动）。
在 **(2) train from COCO weights(recommend):** 里边做到 python train.py 时，总也导入不了 yolov3_coco_demo.ckpt.
总是说
=> ./checkpoint/yolov3_coco_demo.ckpt does not exist !!!
=> Now it starts to train YOLOV3 from scratch ...

在 config.py 里的设置也没错
__C.TRAIN.INITIAL_WEIGHT        = "./checkpoint/yolov3_coco_demo.ckpt"

请问有人遇到过这样的问题么？

**Comment by FangliangBai** [comment]
解决了，是因为我没有严格按照步骤来，不是代码的问题。
在convert weights的时候用的了一个数据的class.names，train的时候用了另一个class.names. 两个类数目不同，导致了网络output的时候output feature map 的 shape不同，所以graph就不一样了，出现了无法导入的错误。

**Comment by yunyao01** [comment]
@FangliangBai 你好，我也遇到了相同的问题： ./checkpoint/yolov3_coco_demo.ckpt does not exist 
然后代码接着会训练，结果训练出的文件900对M，所以想问下你的训练出的文件有多大？

**Comment by Shame-fight** [comment]
我遇到了相同的错误，可以解答一下吗？非常感谢 @FangliangBai @yunyao01

**Comment by nengbunengzhengdianqi** [comment]
可能是由于你没有运行前面的”python convert_weight.py --train_from_coco“
