### ISSUE TITLE
Small typos in two files

### ISSUE THREAD

**Issue by FangliangBai** [YunYang1994/tensorflow-yolov3#185]
I found two typos:

1. > Then you will get some .pb files in the dir ./checkpoint, and run the demo script

The .pb file is located in the root path.

2. https://github.com/YunYang1994/tensorflow-yolov3/blob/8815c6f77ecfe5666b5722a3ff9b8b86a22f86c0/core/utils.py#L65

should be
```py
"""
bboxes: [x_min, y_min, x_max, y_max, probability, cls_id] format coordinates.
"""
```

**Comment by YunYang1994** [comment]
Thank you. I've fixed it .
