### ISSUE TITLE
多GPU训练的问题

### ISSUE THREAD

**Issue by zengqi0730** [YunYang1994/tensorflow-yolov3#267]
我将train.py修改成了多GPU训练模式，可以正常训练得到ckpt文件，但是运行freeze_graph.py将保存的ckpt文件转成pb文件的时候，却提示错误 
NotFoundError (see above for traceback): Key conv52/batch_normalization/beta not found in checkpoint
请问会是什么原因？

**Comment by zengqi0730** [comment]
问题已解决！ scope命名问题导致

**Comment by MichaelCong** [comment]
> 问题已解决！ scope命名问题导致

你好，能看一下你多GPU训练的代码吗

**Comment by hangxu124** [comment]
> 问题已解决！ scope命名问题导致

您好，能详细的说下是哪里错了么？

**Comment by tradysun** [comment]
> 问题已解决！ scope命名问题导致

能否分享一下train.py支持多GPU的代码
