### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by jiaweichen168** [YunYang1994/tensorflow-yolov3#29]
File "train.py", line 44, in <module>
    loss = model.compute_loss(y_pred, y_true)
  File ".../tensorflow-yolov3/core/yolov3.py", line 269, in compute_loss
    loss_class += result[3]
IndexError: tuple index out of range

**Comment by Lechatelia** [comment]
i  think you can comment 
 # return object_mask, intersect_area, iou_scores
in the  function _loss_layer_ in file` yolov3.py`
i hope it may help you

**Comment by YunYang1994** [comment]
sorry, I haven't updated my code yet. please refer to this repo https://github.com/YunYang1994/tensorflow-yolov2_from_scratch

**Comment by jiaweichen168** [comment]
yolov3，不是比yolov2 速度更快？ 怎么又做回去了？
我先比对一下代码吧。正要训练 COCO

发件人: YangYun [mailto:notifications@github.com]
发送时间: 2019年1月17日 9:51
收件人: YunYang1994/tensorflow-yolov3 <tensorflow-yolov3@noreply.github.com>
抄送: Jiawei Chen <jiawei.chen@cpnet.io>; Author <author@noreply.github.com>
主题: Re: [YunYang1994/tensorflow-yolov3] tuple index out of range (#29)


sorry, I haven't updated my code yet. please refer to this repo https://github.com/YunYang1994/tensorflow-yolov2_from_scratch

**Comment by leo6033** [comment]
I also encountered the same problem, I used my own training set, but I got an error.
![50](https://user-images.githubusercontent.com/39845454/51317424-8165f180-1a92-11e9-9abc-3fb4dfecc695.png)

**Comment by jiaweichen168** [comment]
yolo3.py, comment line 337.

**Comment by madhu-korada** [comment]
Can you please tell which line in the updated code.
