### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint: ./checkpoint/yolov3_coco_demo.ckpt

### ISSUE THREAD

**Issue by Zolich666** [YunYang1994/tensorflow-yolov3#291]
I didn't make any change. When I ran freeze_graph.py, it reported 'ValueError: The passed save_path is not a valid checkpoint: ./checkpoint/yolov3_coco_demo.ckpt'
Anyone knows why? Someone said it was because the path name was too long. But I tried to shorten it and it didn't work.

**Comment by adamgan919191** [comment]
how you slove this problem?

**Comment by Zolich666** [comment]
> how you slove this problem?

Did you meet the same problem? Now I may solve it. I find it's just because the checkpoint file yolov3_coco_demo.ckpt didn't save successfully. I ran the convert_weight.py again. And it worked out!
