### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../yolo_weghts/darknet53.conv.74'

### ISSUE THREAD

**Issue by jiaweichen168** [YunYang1994/tensorflow-yolov3#30]
File "train.py", line 69, in <module>
    weights_file="../yolo_weghts/darknet53.conv.74")
  File "/media/cjw/data/AI_allin/model/computerVision/tensorflow-yolov3/core/utils.py", line 258, in load_weights
    with open(weights_file, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '../yolo_weghts/darknet53.conv.74'

**Comment by qiaomai89** [comment]
you should first download the darknet53.conv.74 file by yourself and put it in the right place

**Comment by jiaweichen168** [comment]
you are right.
