### ISSUE TITLE
test loss降到4左右，但是mAP为0.00

### ISSUE THREAD

**Issue by myrzx** [YunYang1994/tensorflow-yolov3#321]
我只训练了一个类别cow，从README里提供的voc数据集进行筛选，只留下只含cow的图片，最终是165张和39张。
train_from_coco，batch_size=4，训练了27轮，first_stage20轮，second_stage7轮，最终test loss降到4左右，但是运行evaluate.py时和真实情况相差较大，而且mAP也一直是0. 00。
请问这是我样本太少的原因吗？还是test loss得是0.几才行？

**Comment by limingyue123** [comment]
我训练自己的数据得到的mAP也不是很好，就10%左右，30个stage,loss降到8.8左右，你的问题解决了吗

**Comment by navy63** [comment]
不要从头开始训练，

**Comment by myrzx** [comment]
> 不要从头开始训练，

我用的是python train.py --train_from_coco啊

**Comment by myrzx** [comment]
> 我只训练了一个类别cow，从README里提供的voc数据集进行筛选，只留下只含cow的图片，最终是165张和39张。
> train_from_coco，batch_size=4，训练了27轮，first_stage20轮，second_stage7轮，最终test loss降到4左右，但是运行evaluate.py时和真实情况相差较大，而且mAP也一直是0. 00。
> 请问这是我样本太少的原因吗？还是test loss得是0.几才行？

使用自己的数据集，200张训练集，58张测试集，都是比较清晰的图片。test loss降到了1.17，然后mAP100%emmmmm。训练成功，现在应该担心过拟合的问题了。
