### ISSUE TITLE
关于dataset里preprocess_true_box方法

### ISSUE THREAD

**Issue by joshzzl** [YunYang1994/tensorflow-yolov3#326]
你好，在dataset.py, preprocess_true_box方法里你用了一个iou_mask来进行labeling。但是假设在三个small anchor里面有两个都是超过IOU threshold，那么你会把两个都标记为obj? 这个似乎和我理解不太一样，我以为一个ground truth box有且仅有一个对应的anchor box（IOU值最大的那个）。
而且外侧的for loop（215行）我理解的是针对small,medium,large三种boxes进行的loop。那么那个flag - exist_positive 是用来检测9个anchor里面有没有IOU大于thres。但是这个for loop不会因为这个flag变为true而中断，也就是说只要大于thres，一个ground truth box可能同时让small, medium, large三种anchor里标记为label? 这好像也违背了一个ground truth 对应一个anchor的原理。
不知道是不是我对原文章和代码理解错了。谢谢你的implementation。非常感谢。

**Comment by joshzzl** [comment]
我想我知道错在哪里了。每个anchor对应一个gt，但是每个gt可以对应多个anchor。

**Comment by tangchen2** [comment]
> 我想我知道错在哪里了。每个anchor对应一个gt，但是每个gt可以对应多个anchor。

我记得原文就是一个gt对应一个anchor的，preprocess true box中的复现确实有可能出现一个gt对应三种scale中的anchor的情况，我认为这个写法是有问题的，我看过qwe的yolo v3复现，那里面就是一个gt box对应一个anchor的

**Comment by joshzzl** [comment]
> 我记得原文就是一个gt对应一个anchor的，preprocess true box中的复现确实有可能出现一个gt对应三种scale中的anchor的情况，我认为这个写法是有问题的，我看过qwe的yolo v3复现，那里面就是一个gt box对应一个anchor的

谢谢 我去看看。那么obj 和non-obj是如何标定的呢？比如总共有9个anchor分大中小各三个，只有IOU最大的那个算obj，那剩下的我记得应该还是分两种，一种是no-obj（IOU小于threshold）；还有一种是被我们忽略了，好像是不计算loss。不知道你有没有看到qwe那个怎么写的。（IOU大于threshold但是不是max）
