### ISSUE TITLE
关于focal loss的问题

### ISSUE THREAD

**Issue by sunRaisingEast** [YunYang1994/tensorflow-yolov3#328]
尊敬的yunyang先生：
看论文中叙述，使用了focal loss效果并不如从前，在这里，我想做一下伸手党，去掉focal loss的代码有没有。。谢谢！

**Comment by sunRaisingEast** [comment]
是不是直接将conf_focal去掉，感谢不吝指教！

**Comment by jiarenyf** [comment]
请问，去掉focal loss有效果吗？
