### ISSUE TITLE
模型训练异常

### ISSUE THREAD

**Issue by tensorflowt** [YunYang1994/tensorflow-yolov3#333]
![1111](https://user-images.githubusercontent.com/37217594/66011445-bd909380-e4f5-11e9-9eaa-a5e266eb1e97.png)

如图所示，在训练模型的过程中，可以顺利运行4个epoch，但是到第5个就遇到bug，感觉是因为显存的问题，但是，我这里用的是2080ti 11G显存 两块，模型的batch_size已经设置到3了，感觉很奇怪，求大佬指点,不胜感激！

**Comment by w910820618** [comment]
我也遇到这个问题请问你们解决了吗？

**Comment by navy63** [comment]
从loss值来看，你好像是重头训练的，重头训练效果不是太好，你最好还是加载模型训练，分布式训练，最好把第一个epoch设置为30，默认的是20

**Comment by tensorflowt** [comment]
> 从loss值来看，你好像是重头训练的，重头训练效果不是太好，你最好还是加载模型训练，分布式训练，最好把第一个epoch设置为30，默认的是20

你好！我是训练自己的数据，作者提供的原始模型不能做迁移学习，请问为什么第一个epoch需要设置为30呢？

**Comment by landwash** [comment]
我貌似遇到了同样的问题，我是自建数据集训练的，后来跟踪了下发现自己的数据集转换错了，bounding box的xmax和ymax超过了图像的尺寸大小就会报这个错，你检查下是不是同样的错误。

**Comment by tensorflowt** [comment]
> 我貌似遇到了同样的问题，我是自建数据集训练的，后来跟踪了下发现自己的数据集转换错了，bounding box的xmax和ymax超过了图像的尺寸大小就会报这个错，你检查下是不是同样的错误。

IndexError: index 68 is out of bounds for axis 1 with size 60 #223这个方法可以解决。
