### ISSUE TITLE
config.py 中 __C.TRAIN.INPUT_SIZE 和 __C.TEST.INPUT_SIZE 设置的目的是？

### ISSUE THREAD

**Issue by dlutor** [YunYang1994/tensorflow-yolov3#334]
config.py 中 __C.TRAIN.INPUT_SIZE  中原来有[320, 352, 384, 416, 448, 480, 512, 544, 576, 608]，这样设置的原因是什么？__C.TEST.INPUT_SIZE 中有1个数，目的是什么？能设置多个吗？

**Comment by YunYang1994** [comment]
多尺度训练
