### ISSUE TITLE
请问tensorflow与keras对yolov3的性能有差异吗？

### ISSUE THREAD

**Issue by HaiLongEmb** [YunYang1994/tensorflow-yolov3#361]
@YunYang1994  感谢作者的讲解，但有一点没有理解，就是tensorflow实现yolov3与keras实现的yolov3,本质是否一致，我理解的keras是对tensorflow的高度封装，请问这样理解对吗？

感谢各位大神指教

**Comment by YunYang1994** [comment]
TensorFlow 1.0 版本可能会更快一些

**Comment by HaiLongEmb** [comment]
> TensorFlow 1.0 版本可能会更快一些

请问您的意思是tensorflow1.0 要比tensorflow1.0的tf.keras实现的yolov3更快吗？还有现在tensorflow已经到2.0版本了，那2.3版本的keras与tensorflow2.0的tf.keras性能哪个更好，有什么根据吗？

请大神解惑

**Comment by YunYang1994** [comment]
我也在思考这个问题，之前很多人发邮件给我说为什么你的模型比https://github.com/qqwweee/keras-yolo3 快很多。而且用了 tf2 发现，函数型编程模式似乎要比子类模式慢一些？具体我也不太清楚，还望路过的高手解答！

**Comment by YunYang1994** [comment]
https://github.com/keras-team/keras/issues/7818
