### ISSUE TITLE
giou_loss

### ISSUE THREAD

**Issue by robinjoe93** [YunYang1994/tensorflow-yolov3#371]
用自己的数据集从零开始训练，giou_loss在4-6之间波动无法收敛，并且预测出的框的conf最大也只有0.14，而且所有图片预测的位置都在一个地方，很迷惑。是因为训练的epoch太少了吗？

**Comment by HAIbingshuai** [comment]
数据标注的问题吧

**Comment by robinjoe93** [comment]
> 数据标注的问题吧

举个例子：    ../1.jpg 253,1,314,144,0 25,36,128,253,2   
 我觉得我是按照作者readme中的格式标注的呀

**Comment by HAIbingshuai** [comment]
我说的标注指的是 数据量可够？数据类别特征是否统一？标注框是否统一？都等影响最终的giou

**Comment by robinjoe93** [comment]
> 我说的标注指的是 数据量可够？数据类别特征是否统一？标注框是否统一？都等影响最终的giou

是的  都没问题，是公司自己的数据集，数量够，标注框是统一的。
可能是我问题的根源没找到，而giou_loss只是我能看到的一个小问题
我的问题就是训练之后，测试集和训练集的mAP=0，框的位置都在所有图的差不多相同的位置，且confidence的值很低很低
我改了网络的预测类别 我的class=1，感觉输出的pred_box的tensor（？，？，？，3，6）也是对的

**Comment by lulu-Lucas** [comment]
> > 我说的标注指的是 数据量可够？数据类别特征是否统一？标注框是否统一？都等影响最终的giou
> 
> 是的 都没问题，是公司自己的数据集，数量够，标注框是统一的。
> 可能是我问题的根源没找到，而

> 用自己的数据集从零开始训练，giou_loss在4-6之间波动无法收敛，并且预测出的框的conf最大也只有0.14，而且所有图片预测的位置都在一个地方，很迷惑。是因为训练的epoch太少了吗？

请问您解决了吗
