### ISSUE TITLE
报告一个疑似bug

### ISSUE THREAD

**Issue by poirotZhu** [YunYang1994/tensorflow-yolov3#373]
在dataset.py　这个文件中关于gtbox和anchor box计算iou的问题
anchors_xywh = np.zeros((self.anchor_per_scale, 4))
anchors_xywh[:, 0:2] = np.floor(bbox_xywh_scaled[i, 0:2]).astype(np.int32) + 0.5
anchors_xywh[:, 2:4] = self.anchors[i]
iou_scale = self.bbox_iou(bbox_xywh_scaled[i][np.newaxis, :], anchors_xywh)
iou.append(iou_scale)
iou_mask = iou_scale > 0.3

`anchors_xywh[:, 2:4] = self.anchors[i]` 这里应该除以 strides, 也就是self.anchors[i]/self.strides[i]

**Comment by YunYang1994** [comment]
不用除，这个anchor是已经除过了的

**Comment by poirotZhu** [comment]
确实，是在那个anchor的txt文件里面除过了。 不好意思，没有发现这里
