### ISSUE TITLE
IndexError: index A is out of bounds for axis k with size B (B<A)

### ISSUE THREAD

**Issue by jiarenyf** [YunYang1994/tensorflow-yolov3#375]
https://github.com/YunYang1994/tensorflow-yolov3/issues/223#issuecomment-508348173

For those met similar problem, while the solution provided by the author is useless.

**Comment by YunYang1994** [comment]
It seems that the center position of some bounding boxes is out of the range of input image

**Comment by jiarenyf** [comment]
> It seems that the center of some bounding boxes are out of the range of input image. I think you should write a simple script for your dataset to make sure this situation won' t happen.
> 
> Good luck !

I can config that the bounding box in my dataset obey the following rule:

`0<=xmin,xmax<width && 0<=ymin,ymax<height`

So the problem may be caused by another bug ?

**Comment by YunYang1994** [comment]
Did you modify this code ?

**Comment by jiarenyf** [comment]
Never modify the code, but changes the *.names to only one classes.

**Comment by YunYang1994** [comment]
> Never modify the code, but changes the *.names to only one classes.

maybe you feed some images with labeled of one more class , is it right ? Just Check you dataset.

**Comment by jiarenyf** [comment]
It is because that in some cases: xmin == xmax or ymin == ymax.
