### ISSUE TITLE
random_horizontal_flip question

### ISSUE THREAD

**Issue by jiarenyf** [YunYang1994/tensorflow-yolov3#389]
https://github.com/YunYang1994/tensorflow-yolov3/blob/674ef1a95e7457598b5eb13db999e764e3278626/core/dataset.py#L105

Should be: `bboxes[:, [0,2]] = w - bboxes[:, [2,0]] - 1` ...

**Comment by YunYang1994** [comment]
yes, you are right. you can pull request this repo. thank you

**Comment by jiarenyf** [comment]
OK.
