### ISSUE TITLE
单目标检测效果很差，该如何定位问题？

### ISSUE THREAD

**Issue by tradysun** [YunYang1994/tensorflow-yolov3#392]
基于VOC2007数据集构造了多种文字类水印，按单分类的方式进行训练(4000张训练数据)，迭代了80个epoch，total loss能到1.2，但预测效果很差，基本得分都是0.3左右，mAP很低，感觉模型根本没收敛。

**Comment by tradysun** [comment]
![image](https://user-images.githubusercontent.com/24379156/68556470-63c4a700-046d-11ea-8902-babc659252db.png)

**Comment by YunYang1994** [comment]
你倒是上个预测效果图啊？

**Comment by tradysun** [comment]
![image](https://user-images.githubusercontent.com/24379156/68564842-acd82380-048c-11ea-8bad-2b005dfe402c.png)
![image](https://user-images.githubusercontent.com/24379156/68564860-be213000-048c-11ea-84b0-3f3eaf9b6983.png)
![image](https://user-images.githubusercontent.com/24379156/68564886-d729e100-048c-11ea-8941-7f02d82f0f08.png)
感谢作者大大回复，另外我试了把VOC数据中car类的分出来(几百张)训练单分类(names还是只写了watermark),很快迭代80个epoch，最终loss到0.6，预测效果还不错。
![image](https://user-images.githubusercontent.com/24379156/68565369-42c07e00-048e-11ea-9f4d-9ee6c1a0596c.png)
两次实验都是加载了coco预训练权重

**Comment by ylqi007** [comment]
@tradysun 
你好，请教一下。我没太明白你说的把 car 类挑出来，names 只保留 watermark，是只保留 VOC 所有图片中的 car 一个类别，但是在 names 中却将其命名为 watermark 类吗？

我现在在 COCO 上训练，mAP 只有 0.3 ~ 0.4，想问问你是怎么该的，mAP 能提高那么多？

谢谢
