### ISSUE TITLE
在训练自己的数据集的时候报错.

### ISSUE THREAD

**Issue by yijunL** [YunYang1994/tensorflow-yolov3#408]
作者你好！
我的程序运行的时候跑到这一行时报错
image = cv2.warpAffine(image, M, (w, h))

报错内容
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/imgwarp.cpp:2594: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'warpAffine'
请问这是什么原因啊？
而且还是在第二个epoch的时候报的错

再次跑train.py
报错内容
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB).astype(np.float32)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

是数据集有问题吗？

**Comment by yijunL** [comment]
已解决，，原因是数据集中框坐标的顺序错了

**Comment by KAOeric** [comment]
@yijunL sorry to ask for you!  I have the same problem like yours before, could you please tell me how to fix this problem?
Thanks for helping
