### ISSUE TITLE
> 前辈 您好，感谢回复，我利用博主给的voc模型是可以生成pb文件的，我自己训练的模型，无法专为pb文件，如果您转成功了请赐教。

### ISSUE THREAD

**Issue by yangzhenjie** [YunYang1994/tensorflow-yolov3#457]
> 前辈 您好，感谢回复，我利用博主给的voc模型是可以生成pb文件的，我自己训练的模型，无法专为pb文件，如果您转成功了请赐教。
> 
> 
> 
> 
> 
> 发自我的iPhone
> …
我也遇到过 在sess 的时候需要初始化一次全局变量和局部变量。

_Originally posted by @zhumengbo in https://github.com/YunYang1994/tensorflow-yolov3/issues/39#issuecomment-557461605_

**Comment by kalayan** [comment]
你好，这个请问你解决了吗？怎么解决的呢？

**Comment by wl4135** [comment]
> 你好，这个请问你解决了吗？怎么的呢？
我也是，请问解决了吗？我的报错：
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: /checkpoint : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process
