### ISSUE TITLE
data_aug resulting index outside the box

### ISSUE THREAD

**Issue by ramdhan1989** [YunYang1994/tensorflow-yolov3#473]
data_aug in parse_annotation dataset.py resulting index value outside the array of label in preprocess_true_boxes (dataset.py). So, it is suffered with error (IndexError: index xx is out of bounds for axis 0 with size yy),(xx could be negative?) during training process. please advise how to handle the problem ?

**Comment by fxcdl** [comment]
I got the same problem? Have you solved it？

**Comment by andreeabodea** [comment]
I have the same problem in (dataset.py)  and in (core\dataset.py") IndexError: list index out of range. Have you solved it?

**Comment by fxcdl** [comment]
make sure 0<box_height<image_height, 0<box_width<image_width

**Comment by andreeabodea** [comment]
@fxcdl after the training process you need to export the weights again(generate .pb file)? 
'$ python convert_weight.py'
'$ python freeze_graph.py'

Or once the training is done you just use: '$ python image_demo.py'?
Thank you!

**Comment by ramdhan1989** [comment]
I solved it, please be aware to your data. in my case, it is due to wrong bounding box and corrupt files.
