### ISSUE TITLE
有偿解决也可以的AttributeError: module 'utils' has no attribute 'read_image_box_from_text'有热心人帮我看看吗

### ISSUE THREAD

**Issue by cailong-1** [YunYang1994/tensorflow-yolov3#479]
图像数据集转成.tfrecord，就是用二进制来保存数据    这一步骤的时候出现的下面问题
utils文件没有这个函数吧，若帮助解决有偿付费也是可以的
dataset = utils.read_image_box_from_text(flags.dataset_txt) 
AttributeError: module 'utils' has no attribute 'read_image_box_from_text'

**Comment by EEeEhh** [comment]
> 图像数据集转成.tfrecord，就是用二进制来保存数据 这一步骤的时候出现的下面问题
> utils文件没有这个函数吧，若帮助解决有偿付费也是可以的
> dataset = utils.read_image_box_from_text(flags.dataset_txt)
> AttributeError: module 'utils' has no attribute 'read_image_box_from_text'

你把这个函数补上就可以咯
