### ISSUE TITLE
CPU训练

### ISSUE THREAD

**Issue by GFENGG** [YunYang1994/tensorflow-yolov3#481]
大佬，我，，条件限制，没有GPU可用，我安装了cpu版本的tensorflow，数据集也按您给的例程准备好了。请问我是可以执行python train.py训练了么，需要修改哪里的代码来选择cpu执行训练过程吗？期待回复~谢谢

**Comment by jashonxudawu** [comment]
你好，我也遇到了一样的问题，请问这个问题你解决了吗？

**Comment by 923629877** [comment]
你们好，我也是，请问你们解决了吗？
