### ISSUE TITLE
一个行人目标身上有多个框，如图，这是怎么回事

### ISSUE THREAD

**Issue by forwardxu0129** [YunYang1994/tensorflow-yolov3#484]
![re01_20180308_162146_s00_ct_sn_002981](https://user-images.githubusercontent.com/45676881/75539301-fdcc5180-5a54-11ea-919b-15309f9f647b.jpg)

**Comment by forwardxu0129** [comment]
是因为nms算法没有排除掉非极大值嘛

**Comment by forwardxu0129** [comment]
@YunYang1994

**Comment by EEeEhh** [comment]
> 是因为nms算法没有排除掉非极大值嘛

调整测试时候的IOU_threshold就可以了。

**Comment by YunYang1994** [comment]
这是因为 nms 是针对每个类别进行的，如果将所有类别的框一起 nms，就不会出现这种情况。
