### ISSUE TITLE
image_demo.py和video_demo.py中，是否重复使用了cv2.COLOR_BGR2RGB)？

### ISSUE THREAD

**Issue by kimi-zy** [YunYang1994/tensorflow-yolov3#493]
![image](https://user-images.githubusercontent.com/50159318/76452089-77781e00-640b-11ea-94d8-32aef62183d9.png)
![image](https://user-images.githubusercontent.com/50159318/76452101-79da7800-640b-11ea-9604-c60679fd0922.png)
仓主您好，非常感谢可以学习您的代码。

直接使用您训练好的权重来运行video_demo.py, 画框都是正常的。

不过我在用这一版代码做自己的数据集训练时，遇到如下问题：

- 50个epochs后，loss小于1，但测试的效果很差，即使用image_demo.py给训练集的图片画框，也是错的；

- 而把image_demo.py中“cv2.cvtColor(original_image, cv2.COLOR_BGR2RGB)”注释掉后，预测及画框是正常了（生成的图片颜色似乎还有点异常）。

请仓主您看看这一版代码是否存在这个问题。

**Comment by TianFuKang** [comment]
yes
