### ISSUE TITLE
anchor的尺度是用kmeans聚类整个数据集还是只聚类训练集啊？

### ISSUE THREAD

**Issue by tinothy22** [YunYang1994/tensorflow-yolov3#500]
为什么我聚类了训练集，map还掉了0.9个点.....

**Comment by wl4135** [comment]
> 为什么我聚类了训练集，map还掉了0.9个点.....

应该是聚类训练集，我的map掉了2个点，正在查找原因

**Comment by tinothy22** [comment]
我也掉点....我聚类了整个数据集，和baseline相比我掉了0.3个百分点------------------ 原始邮件 ------------------
发件人: "wanglei"<notifications@github.com>
发送时间: 2020年3月23日(星期一) 晚上9:33
收件人: "YunYang1994/tensorflow-yolov3"<tensorflow-yolov3@noreply.github.com>;
抄送: "tinothy22"<837965445@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [YunYang1994/tensorflow-yolov3] anchor的尺度是用kmeans聚类整个数据集还是只聚类训练集啊？ (#500)




  
为什么我聚类了训练集，map还掉了0.9个点.....
  
应该是聚类训练集，我的map掉了2个点，正在查找原因
 
&mdash;

**Comment by wl4135** [comment]
> 我也掉点....我聚类了整个数据集，和baseline相比我掉了0.3个百分点------------------ 原始邮件 ------------------ 发件人: "wanglei"<notifications@github.com> 发送时间: 2020年3月23日(星期一) 晚上9:33 收件人: "YunYang1994/tensorflow-yolov3"<tensorflow-yolov3@noreply.github.com>; 抄送: "tinothy22"<837965445@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [YunYang1994/tensorflow-yolov3] anchor的尺度是用kmeans聚类整个数据集还是只聚类训练集啊？ (#500) 为什么我聚类了训练集，map还掉了0.9个点..... 应该是聚类训练集，我的map掉了2个点，正在查找原因 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我想我的聚类的结果和最后的计算结果出错了，继续尝试一下，看看效果

**Comment by wl4135** [comment]
我又重新聚类后，分别除以8，16，32得到9个值，比之前直接重新聚类提升4个点，比应用原版的anchors提升两个点

**Comment by yinhai86924** [comment]
> 我又重新聚类后，分别除以8，16，32得到9个值，比之前直接重新聚类提升4个点，比应用原版的anchors提升两个点

请问有生成anchors的代码吗

**Comment by Wenzhe-Liang** [comment]
> 我又重新聚类后，分别除以8，16，32得到9个值，比之前直接重新聚类提升4个点，比应用原版的anchors提升两个点

请问如何聚类自己的anchors呢，是用作者项目里的哪个脚本啊

**Comment by JerryIndus** [comment]
> 为什么我聚类了训练集，map还掉了0.9个点.....

想请问一下您聚类之后的值需要反归一化么，我聚类完都是小数

**Comment by 1317729246** [comment]
> 我又重新聚类后，分别除以8，16，32得到9个值，比之前直接重新聚类提升4个点，比应用原版的anchors提升两个点

请问重新聚类后还需要什么处理吗？
