### ISSUE TITLE
训练几个echoes之后，会出错IndexError: index 77 is out of bounds for axis 0 with size 76

### ISSUE THREAD

**Issue by CNUyue** [YunYang1994/tensorflow-yolov3#502]
在我运行训练的时候前几个echoes都跑到好好的，但是下一个echoe就会出错
 File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "/workspace/tensorflow-yolov3-master/core/dataset.py", line 76, in __next__
    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
  File "/workspace/tensorflow-yolov3-master/core/dataset.py", line 234, in preprocess_true_boxes
    label[i][yind, xind, iou_mask, :] = 0
IndexError: index 77 is out of bounds for axis 0 with size 76
请问这是什么问题@YunYang1994

**Comment by cydawn** [comment]
我也是这个类型的报错，也不知道是那张图片出了问题

**Comment by wl4135** [comment]
> 在我运行训练的时候前几个echoes都跑到好好的，但是下一个echoe就会出错
> File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 930, in **iter**
> for obj in iterable:
> File "/workspace/tensorflow-yolov3-master/core/dataset.py", line 76, in **next**
> label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
> File "/workspace/tensorflow-yolov3-master/core/dataset.py", line 234, in preprocess_true_boxes
> label[i][yind, xind, iou_mask, :] = 0
> IndexError: index 77 is out of bounds for axis 0 with size 76
> 请问这是什么问题@YunYang1994

我也遇到了同样的问题，请问您解决了吗？

**Comment by CNUyue** [comment]
还没有解决，您解决了吗

**Comment by CNUyue** [comment]
请问您是怎么解决的，这个应该不是label的问题吧，要不然前面几个echoe也跑不下来@cydawn

**Comment by wl4135** [comment]
我也没解决，我是数据增强后出得问题，还没训练就抱这个错误，我查了查应该是是增强后的xml文件的问题。重新做数据再试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CNUyue <notifications@github.com>
发送时间: 2020年3月29日 15:25
收件人: YunYang1994/tensorflow-yolov3 <tensorflow-yolov3@noreply.github.com>
抄送: wanglei <1804068@mails.ccu.edu.cn>, Comment <comment@noreply.github.com>
主题: 回复：[YunYang1994/tensorflow-yolov3] 训练几个echoes之后，会出错IndexError: index 77 is out of bounds for axis 0 with size 76 (#502)





 
还没有解决，您解决了吗

**Comment by cydawn** [comment]
> 请问您是怎么解决的，这个应该不是label的问题吧，要不然前面几个echoe也跑不下来@cydawn
我看了之前的issue全是label的问题，我就去查了一下发现确实是label的问题

**Comment by wl4135** [comment]
> > 
> 
> > 请问您是怎么解决的，这个应该不是label的问题吧，要不然前面几个echoe也跑不下来@cydawn
> 
> 我看了之前的issue全是label的问题，我就去查了一下发现确实是label的问题

您好，您的检查脚本是怎么写的呢？方便分享一下吗？谢谢您

**Comment by cydawn** [comment]
> 
import cv2
import numpy as np
path = ""  ##pic path
name = []
bbox = []
with open("./voc_train.txt","r") as vocfile:    ##change your file‘s path
    for lines in vocfile.readlines():
        line = lines.split(' ')
        name.append(line[0].split('/')[-1])
        bbox.append(np.array([list(map(lambda x: int(float(x)), box.split(','))) for box in line[1:]]))
wrongnames = []
for i in range(len(name)):
    image = cv2.imread(path + name[i])
    shape = image.shape
    for box in bbox[i]:
        if box[0] < 0 or box[0] > shape[1] or box[2] < 0 or box[2] > shape[1] or box[1] < 0 or box[1] > shape[0] or box[3] < 0 or box[3] > shape[0] or box[4] != 0:
            wrongnames.append(name[i])
            print(name[i] + "  wrong")
        else:
            print(str(i) + "  right")
print("done")
print(wrongnames)
> 
@wl4135 代码写的一般，你就将就着用吧

**Comment by wl4135** [comment]
> > 
> 
> import cv2
> import numpy as np
> path = "" ##pic path
> name = []
> bbox = []
> with open("./voc_train.txt","r") as vocfile: ##change your file‘s path
> for lines in vocfile.readlines():
> line = lines.split(' ')
> name.append(line[0].split('/')[-1])
> bbox.append(np.array([list(map(lambda x: int(float(x)), box.split(','))) for box in line[1:]]))
> wrongnames = []
> for i in range(len(name)):
> image = cv2.imread(path + name[i])
> shape = image.shape
> for box in bbox[i]:
> if box[0] < 0 or box[0] > shape[1] or box[2] < 0 or box[2] > shape[1] or box[1] < 0 or box[1] > shape[0] or box[3] < 0 or box[3] > shape[0] or box[4] != 0:
> wrongnames.append(name[i])
> print(name[i] + " wrong")
> else:
> print(str(i) + " right")
> print("done")
> print(wrongnames)
> 
> > 
> 
> @wl4135 代码写的一般，你就将就着用吧

好的，非常感谢您

**Comment by MuhammadAsadJaved** [comment]
> > 
> 
> import cv2
> import numpy as np
> path = "" ##pic path
> name = []
> bbox = []
> with open("./voc_train.txt","r") as vocfile: ##change your file‘s path
> for lines in vocfile.readlines():
> line = lines.split(' ')
> name.append(line[0].split('/')[-1])
> bbox.append(np.array([list(map(lambda x: int(float(x)), box.split(','))) for box in line[1:]]))
> wrongnames = []
> for i in range(len(name)):
> image = cv2.imread(path + name[i])
> shape = image.shape
> for box in bbox[i]:
> if box[0] < 0 or box[0] > shape[1] or box[2] < 0 or box[2] > shape[1] or box[1] < 0 or box[1] > shape[0] or box[3] < 0 or box[3] > shape[0] or box[4] != 0:
> wrongnames.append(name[i])
> print(name[i] + " wrong")
> else:
> print(str(i) + " right")
> print("done")
> print(wrongnames)
> 
> > 
> 
> @wl4135 代码写的一般，你就将就着用吧

@cydawn @wl4135 

Can you please share   .py file ?    asadjavedgujar@gmail.com

**Comment by zhouth94** [comment]
> > > 
> > 
> > 
> > import cv2
> > import numpy as np
> > path = "" ##pic path
> > name = []
> > bbox = []
> > with open("./voc_train.txt","r") as vocfile: ##change your file‘s path
> > for lines in vocfile.readlines():
> > line = lines.split(' ')
> > name.append(line[0].split('/')[-1])
> > bbox.append(np.array([list(map(lambda x: int(float(x)), box.split(','))) for box in line[1:]]))
> > wrongnames = []
> > for i in range(len(name)):
> > image = cv2.imread(path + name[i])
> > shape = image.shape
> > for box in bbox[i]:
> > if box[0] < 0 or box[0] > shape[1] or box[2] < 0 or box[2] > shape[1] or box[1] < 0 or box[1] > shape[0] or box[3] < 0 or box[3] > shape[0] or box[4] != 0:
> > wrongnames.append(name[i])
> > print(name[i] + " wrong")
> > else:
> > print(str(i) + " right")
> > print("done")
> > print(wrongnames)
> > > 
> > 
> > 
> > @wl4135 代码写的一般，你就将就着用吧
> 
> @cydawn @wl4135 @MuhammadAsadJaved 
> 
> Can you please share .py file ?  
Thanks! To my email : zhouthfish@163.com
