### ISSUE TITLE
请问在运行evalute.py时只输出了ground-truth没有输出predict result,然后main.py时报错ValueError: not enough values to unpack (expected 2, got 0)应该如何解决？

### ISSUE THREAD

**Issue by Kazusa853** [YunYang1994/tensorflow-yolov3#516]

**Comment by Kazusa853** [comment]
Traceback (most recent call last):
  File "main.py", line 737, in <module>
    true_p_bar
  File "main.py", line 183, in draw_plot_func
    sorted_keys, sorted_values = zip(*sorted_dic_by_value)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by Kazusa853** [comment]
=> ground truth of VOC2007\JPEGImages\apple_90.jpg:
        apple 58 124 1776 1910
=> predict result of VOC2007\JPEGImages\apple_90.jpg:
=> ground truth of VOC2007\JPEGImages\banana_93.jpg:
        banana 100 64 381 190
        banana 95 280 380 405
=> predict result of VOC2007\JPEGImages\banana_93.jpg:
=> ground truth of VOC2007\JPEGImages\orange_27.jpg:
        orange 45 57 214 212
        orange 164 49 324 212
        orange 226 2 368 143
=> predict result of VOC2007\JPEGImages\orange_27.jpg:

**Comment by wl4135** [comment]
> => ground truth of VOC2007\JPEGImages\apple_90.jpg:
> apple 58 124 1776 1910
> => predict result of VOC2007\JPEGImages\apple_90.jpg:
> => ground truth of VOC2007\JPEGImages\banana_93.jpg:
> banana 100 64 381 190
> banana 95 280 380 405
> => predict result of VOC2007\JPEGImages\banana_93.jpg:
> => ground truth of VOC2007\JPEGImages\orange_27.jpg:
> orange 45 57 214 212
> orange 164 49 324 212
> orange 226 2 368 143
> => predict result of VOC2007\JPEGImages\orange_27.jpg:
我也是evaluate.py预测不到任何的东西，map为0%，

**Comment by wl4135** [comment]
> => ground truth of VOC2007\JPEGImages\apple_90.jpg:
> apple 58 124 1776 1910
> => predict result of VOC2007\JPEGImages\apple_90.jpg:
> => ground truth of VOC2007\JPEGImages\banana_93.jpg:
> banana 100 64 381 190
> banana 95 280 380 405
> => predict result of VOC2007\JPEGImages\banana_93.jpg:
> => ground truth of VOC2007\JPEGImages\orange_27.jpg:
> orange 45 57 214 212
> orange 164 49 324 212
> orange 226 2 368 143
> => predict result of VOC2007\JPEGImages\orange_27.jpg:

之前我是可以用的，但是最近不知道evaluate.py怎么回事检测不出来，之前我train 的map在90%左右

**Comment by wl4135** [comment]
> => ground truth of VOC2007\JPEGImages\apple_90.jpg:
> apple 58 124 1776 1910
> => predict result of VOC2007\JPEGImages\apple_90.jpg:
> => ground truth of VOC2007\JPEGImages\banana_93.jpg:
> banana 100 64 381 190
> banana 95 280 380 405
> => predict result of VOC2007\JPEGImages\banana_93.jpg:
> => ground truth of VOC2007\JPEGImages\orange_27.jpg:
> orange 45 57 214 212
> orange 164 49 324 212
> orange 226 2 368 143
> => predict result of VOC2007\JPEGImages\orange_27.jpg:

我的是这样解决的，又多训练了40个epochs,再检测就出现预测的物体了，但是有一点过拟合，也可能是数据少的原因

**Comment by CNUyue** [comment]
我也是预测不到任何东西，map=0%,多加一些epochs会有用吗@wl4235

**Comment by wl4135** [comment]
我是这么做的，因为我看评论有的说将evalute.py文件里面的trainable:false改为true我试了，确实可以检测到但是效果很差，于是我按照另外一种增加epochs数目，训练后再检测就可以了，但是多少有点过拟合，增加数据多训练应该就没什么问题了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CNUyue <notifications@github.com>
发送时间: 2020年4月17日 18:02
收件人: YunYang1994/tensorflow-yolov3 <tensorflow-yolov3@noreply.github.com>
抄送: wanglei <1804068@mails.ccu.edu.cn>, Comment <comment@noreply.github.com>
主题: 回复：[YunYang1994/tensorflow-yolov3] 请问在运行evalute.py时只输出了ground-truth没有输出predict result,然后main.py时报错ValueError: not enough values to unpack (expected 2, got 0)应该如何解决？ (#516)





 
我也是预测不到任何东西，map=0%,多加一些epochs会有用吗@wl4235
