### ISSUE TITLE
作者最近有实现tensorflow-yolov4的计划吗

### ISSUE THREAD

**Issue by chunleiml** [YunYang1994/tensorflow-yolov3#522]
darknet版本的训练感觉有点慢

**Comment by zcunyi** [comment]
我也是期待作者更新yolov4

**Comment by wl4135** [comment]
期待

**Comment by miemie2013** [comment]
> darknet版本的训练感觉有点慢

广告虽可耻，大家可以看看我复现的这版yolov4，精心设计了损失函数，训练了70000步就没出现过nan，mAP至少可达36%，欢迎点star：

https://github.com/miemie2013/Keras-YOLOv4

**Comment by miemie2013** [comment]
> 我也是期待作者更新yolov4

广告虽可耻，大家可以看看我复现的这版yolov4，精心设计了损失函数，训练了70000步就没出现过nan，mAP至少可达36%，欢迎点star：

https://github.com/miemie2013/Keras-YOLOv4

**Comment by miemie2013** [comment]
> 期待

广告虽可耻，大家可以看看我复现的这版yolov4，精心设计了损失函数，训练了70000步就没出现过nan，mAP至少可达36%，欢迎点star：

https://github.com/miemie2013/Keras-YOLOv4

**Comment by YunYang1994** [comment]
计划在安排中，后续有的话会通知，谢谢！
