### ISSUE TITLE
加载预训练模型，训练自己的数据

### ISSUE THREAD

**Issue by xinghuokang** [YunYang1994/tensorflow-yolov3#538]
@YunYang1994 
你好，感谢您分享代码资源，在研究代码的时候，想训练自己的数据，只检测一类目标，因为数据不是很多，想fine-tune模型，但是一直加载失败，无法微调。
具体运行见下图所示：
![screenshot](https://user-images.githubusercontent.com/30923040/82966636-e40fbb80-9ffd-11ea-99c9-fc86d0d09edf.png)
![screenshot_1](https://user-images.githubusercontent.com/30923040/82966650-ea059c80-9ffd-11ea-942f-316d631bf4fa.png)

**Comment by xinghuokang** [comment]
如果使用coco.name（80类），是可以加载成功

**Comment by jersonal** [comment]
> 如果使用coco.name（80类），是可以加载成功

我也遇到了同样的问题，用了一种解决方法，但是我的方法会导致如果中断后继续训练,loss会重新开始，请问您解决了吗

**Comment by jersonal** [comment]
@YunYang1994

**Comment by xinghuokang** [comment]
我也实验了，确实重新训练，LOSS有问题，估计预测也会有问题

**Comment by xinghuokang** [comment]
应该是多阶段训练，模型加载的问题。即使是用coco.names(80类目标)，中断后，恢复训练，如果恢复的模型epoch在第一阶段内（作者默认为20），则可以加载成功，如果恢复的模型是在第二阶段，依然会报模型不存在的问题

**Comment by xinghuokang** [comment]
恢复第一阶段内保存的模型，损失是在恢复点继续下降，如果是恢复第二阶段的模型，损失还是感觉重新开始（非常大的LOSS），还在解决问题中。。。。。

**Comment by xinghuokang** [comment]
@jersonal 这个解决了，按照你说的添加了部分代码后可以加载成功，但是中断训练后，在加载会出现损失很大，并没有继续训练，还得修改一些代码，如图所示：
![image](https://user-images.githubusercontent.com/30923040/83110474-b4dc7580-a0f5-11ea-9035-02ed9d98e5d5.png)
加载作者提供的预训练模型的时候，可以添加上述代码块。但是自己训练之后，重新恢复训练的话，需要去除上述代码块（红色框）。
并且还需要修改如下部分代码，直接从第二阶段开始训练，不要再从第一阶段开始训练：
![image](https://user-images.githubusercontent.com/30923040/83110670-fd942e80-a0f5-11ea-8203-c42fa21f4b29.png)
