### ISSUE TITLE
GPU memory out when training with BATCH_SIZE=8  in SECOND_STAGE

### ISSUE THREAD

**Issue by dapsjj** [YunYang1994/tensorflow-yolov3#542]
I used `BATCH_SIZE=8` in `FISRT_STAGE_EPOCHS`  for training,there is no problem,but when I used `BATCH_SIZE=8` in `SECOND_STAGE_EPOCHS`  for training,the error message is memory out.
My GPU is RTX 2070,where is wrong?

**Comment by xinghuokang** [comment]
GPU内存太小了，我用的TitanXp 12G，都没法用batch=8进行第二阶段训练

**Comment by dapsjj** [comment]
> GPU内存太小了，我用的TitanXp 12G，都没法用batch=8进行第二阶段训练
OK!

**Comment by dapsjj** [comment]
> GPU内存太小了，我用的TitanXp 12G，都没法用batch=8进行第二阶段训练

OK，thank you for your reply.

**Comment by Derekabc** [comment]
I used batch_size = 6 and 2080 Ti. It shows out of memory!! How to solve it?

**Comment by leo-XUKANG** [comment]
@Derekabc  set batch_size=2 or 4
