### ISSUE TITLE
Anyone has trained darknet53 on coco 2017?

### ISSUE THREAD

**Issue by tabsun** [YunYang1994/tensorflow-yolov3#58]
It’s a nice work but my trained darknet53 on coco trainval2017 is always not good(about 0.33 for AP50). Can anyone give me some advice? REALLY much thanks

**Comment by ardianumam** [comment]
Me too. I already train from the scratch for about 3 weeks. On training data, the mAP is good enough, about 60%, but the recall is very low, only about 16%.

**Comment by Ragas99205** [comment]
@tabsun @ardianumam Can you guys help in training my model. Actually, I was training this model with raccoon dataset but then when I freeze model and predict object it just predicts raccoon and not other objects from coco dataset. I tried changing the -nc parameter to 81 while freezing but it gave me an error. So can anyone help me with steps?

**Comment by mkartikkumar** [comment]
> @tabsun @ardianumam Can you guys help in training my model. Actually, I was training this model with raccoon dataset but then when I freeze model and predict object it just predicts raccoon and not other objects from coco dataset. I tried changing the -nc parameter to 81 while freezing but it gave me an error. So can anyone help me with steps?

If you train on Racoon dataset, your model is fit for only that, do you want to add racoon as a new class above coco's 80 classes??

While training, we train our classifiers, so it must have all classes what we expect them to predict later

**Comment by Ragas99205** [comment]
@mkartikkumar Thank you for your response. Yes, I want to train raccoon dataset on top of 80 coco classes. Do I have to train again for those coco classes or do I have to make necessary changes in coco_labels.txt after training on raccoon dataset?

**Comment by wenredo** [comment]
So as I understand so far, it is not possible at the moment to train a dataset from scrtch?

**Comment by wenredo** [comment]
From scratch I mean giving as input the darknet53 weights files as darknet53.pb, a new dataset and a new list of classes

**Comment by tabsun** [comment]
Anyone has this problem can try to take imagenet pretrained model as init. This really help a lot. And maybe for those small dataset, you can try train from scratch although I haven't try it.

**Comment by thoang3** [comment]
Hi everyone,

I confirm that the mAP@50 when training from scratch is only 33%, after 30 epochs of training. I use default config which the author shared to have achieved mAP@50 of 63%. 
This is a huge difference!! Does anybody have any insight/experience regarding this?
Thank you in advance!

![mAP_COCO2017_30epochs](https://user-images.githubusercontent.com/9111479/66859614-77e5b900-ef40-11e9-9334-0b8dec08dd8e.png)

**Comment by ylqi007** [comment]
@thoang3 
Hi, thoang3,
Did you train from scratch on COCO dataset, and which COCO dataset did you use?
How about your result right now? Do you get the result 63%?

Sincerey
