### ISSUE TITLE
Tensorflow 2

### ISSUE THREAD

**Issue by willbattel** [YunYang1994/tensorflow-yolov3#80]
@YunYang1994 have you been following developments with TF2? Are there plans to make this library compatible with it on release later this year?

Thanks!

EDIT: I just noticed your Tensorflow 2 Examples repository- so clearly you've been following it! Still wondering about compatibility with this library.

**Comment by YunYang1994** [comment]
Yeah, It's on my plan, but I am quite busy right now. I can't promise any particular date.

**Comment by willbattel** [comment]
Okay, good to know. Thanks again.

**Comment by zzh8829** [comment]
@willbattel if you are still interested, I implemented Yolo from scratch in TensorFlow 2.0 
https://github.com/zzh8829/yolov3-tf2
