### ISSUE TITLE
检测框画的不对

### ISSUE THREAD

**Issue by shifangyan** [YunYang1994/tensorflow-yolov3#98]
我转换啥的都没问题，都是默认，最后执行了nms那个脚本后得到检测结果，得到的结果类别和概率没问题，就框位置不对。看附图，求解惑。
![TIM图片20190331005504](https://user-images.githubusercontent.com/28282624/55279096-84f9dc80-534f-11e9-8fd5-e057762a2662.jpg)

**Comment by YunYang1994** [comment]
> 我转换啥的都没问题，都是默认，最后执行了nms那个脚本后得到检测结果，得到的结果类别和概率没问题，就框位置不对。看附图，求解惑。
> ![TIM图片20190331005504](https://user-images.githubusercontent.com/28282624/55279096-84f9dc80-534f-11e9-8fd5-e057762a2662.jpg)

你改变了输入尺寸吧，我记得draw_box函数有一个需要你输入尺寸的参数

**Comment by shifangyan** [comment]
在core/utils.py的画框函数里面 有个小Bug
ratio = original_size / detection_size
你在还原的时候，这个ratio做了整除除法，导致它一直为1，我把其中一个数改为float就OK了

**Comment by shifangyan** [comment]
> 
> 
> > 我转换啥的都没问题，都是默认，最后执行了nms那个脚本后得到检测结果，得到的结果类别和概率没问题，就框位置不对。看附图，求解惑。
> > ![TIM图片20190331005504](https://user-images.githubusercontent.com/28282624/55279096-84f9dc80-534f-11e9-8fd5-e057762a2662.jpg)
> 
> 你改变了输入尺寸吧，我记得draw_box函数有一个需要你输入尺寸的参数
